従業員一覧の並び順
yasumoto-naoya-organization/ex-emp-management-bugfix pull request #3
Opened 2024-06-06 08:01 UTC by noy-ing

3-1従業員一覧の並び順を入社日の昇順に変更しました

2024-06-06 08:46 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2024-06-06 08:46 UTC, igamasayuki commented on src/main/java/com/example/repository/EmployeeRepository.java
> +		String sql = "SELECT id,name,image,gender,hire_date,mail_address,zip_code,address,telephone,salary,characteristics,dependents_count FROM employees ORDER BY hire-date ASC;";
hire-dateではなくhire_dateだと思います。
動作確認お願いします。

私の認識が間違っていたらお声がけください。

2024-06-07 04:37 UTC, noy-ing commented
ご指摘ありがとうございます。
ご指摘通り-ではなく_でした。
ご指摘箇所修正しましたので確認お願いいたします。

2024-06-07 05:43 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2024-06-07 05:43 UTC, merged